### ISSUE TITLE
Researching the Blogger API v3

### ISSUE THREAD

**Issue by ahmadafrasiyab** [lbrown51/Global-Tactics-Mobile#43]
### Description
As a user, I would like to be able to get posts from global tactics blogger site because I want to show them in the GT app blogs fragment.

### Acceptance Criteria - This story will be complete when
- [ ] PR adds the functionality described above
- [ ] Tests have been added that confirm the functionality of the feature.
- [ ] All tests pass locally and on CircleCI

**Comment by ahmadafrasiyab** [comment]
Two simple requests to get the GT blog and the posts within it:

1. GT blog, request type GET, URL https://www.googleapis.com/blogger/v3/blogs/5044990419048085041?key=[OUR API KEY]
2. Posts on GT blog, request type GET, URL https://www.googleapis.com/blogger/v3/blogs/5044990419048085041/posts?key=[OUR API KEY]

**Comment by ahmadafrasiyab** [comment]
The requests have been saved in a postman collection for reference and use. The link can be found here:
https://www.getpostman.com/collections/4fd562dac56e7bb295fd

**Comment by ahmadafrasiyab** [comment]
@penn2014 @lbrown51 @SamRicha can you guys just review the links I have posted and if they are delivering what they say they are and then we can close this one. I'll make a separate issue for the blogs fragment development.

**Comment by farhadbahrehmandhenry** [comment]
thanks Afrasiyab, looking forward to seeing how these blog posts look in the app. good job
